// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrssfibumfmijjfntdcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyc3NmaWJ1bWZtaWpqZm50ZGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODk2MDIsImV4cCI6MjA3MDY2NTYwMn0.13PP6W5aBSF1nAYzAkCa3O-ZsEu4AiVXikoKKMJQx5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});